"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 3.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os
from core.conf import conf

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-&u7^hof8x_&b(&1=44hy9l89rx=*ski_!0kt%sn3wzusn!$-*l'

# SECURITY WARNING: don't run with debug turned on in production!
COMPANY_NAME = conf.get("COMPANY_NAME")
FULL_COMPANY_NAME = conf.get("FULL_COMPANY_NAME")
DEV_NAME = conf.get("DEV_NAME")
DEBUG = True
TERMS_CONDITION = conf.get("TERMS_CONDITION")

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'src',
    'rest_framework',
    'corsheaders',
    'pwa',
    'webpush',
    'wkhtmltopdf',
]

# REST_FRAMEWORK = {
#     # Use Django's standard `django.contrib.auth` permissions,
#     # or allow read-only access for unauthenticated users.
#     'DEFAULT_PERMISSION_CLASSES': [
#         # 'rest_framework.permissions.IsAuthenticated'
#         'rest_framework.permissions.AllowAny',
#     ],
# }

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': str(os.path.join(BASE_DIR, "db.sqlite3"))
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

DATA_UPLOAD_MAX_NUMBER_FIELDS = 10240 # higher than the count of fields
DATA_UPLOAD_MAX_MEMORY_SIZE = 52428800
# Set directory permissions to allow Django to create subdirectories within MEDIA_ROOT
FILE_UPLOAD_DIRECTORY_PERMISSIONS = 0o755

MEDIA_URL = '/media/'

MEDIA_ROOT = os.path.join(BASE_DIR,'media')

AUTH_USER_MODEL = 'src.Account'# settings.py
REMEMBER_ME_DURATION = 2630000  # One month, in seconds

# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp-mail.outlook.com'
# # EMAIL_HOST = 'smtp.live.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'cswms-system@hotmail.com'
# EMAIL_HOST_PASSWORD = 'Cswms321System!'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'wolf.mschosting.com'
# EMAIL_HOST = 'smtppro01.mschosting.com'
EMAIL_PORT = 587 
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'no-reply@cidblink.com'
EMAIL_HOST_PASSWORD = '1234CIDB@'

# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Etc/GMT-8'
USE_TZ = True


# CORS allow
# CORS_ORIGIN_ALLOW_ALL = True
CORS_ORIGIN_ALLOW_ALL = False
CORS_ORIGIN_WHITELIST = (
  'http://localhost:8000',
  'http://127.0.0.1:8000',
  'https://staging.expat.cidblink.com',
  'https://expat.cidblink.com'
)
CSRF_TRUSTED_ORIGINS = [
  'http://localhost:8000',
  'http://127.0.0.1:8000',
  'https://staging.expat.cidblink.com',
  'https://expat.cidblink.com'
]

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATICFILES_DIRS = [
    os.path.join(BASE_DIR,'static'),
    #'/usr/local/lib/python3.7/dist-packages/django/contrib/admin/static',
]


# SESSION_COOKIE_AGE = 3600  # 1 hour in seconds
SESSION_EXPIRE_AT_BROWSER_CLOSE = False

LOGIN_URL = '/'

# pwa settings
# PWA_APP_DEBUG_MODE = False # dissable console log
PWA_SERVICE_WORKER_PATH = os.path.join(BASE_DIR,'src', 'static', 'serviceworker.js')
PWA_APP_NAME = COMPANY_NAME
PWA_APP_DESCRIPTION = PWA_APP_NAME# + "Admin Dashboard."
PWA_APP_THEME_COLOR = '#c8ffce'
PWA_APP_BACKGROUND_COLOR = '#c8ffce'
PWA_APP_DISPLAY = 'standalone'
PWA_APP_SCOPE = '/'
PWA_APP_ORIENTATION = 'portrait'
PWA_APP_START_URL = '/'
#PWA_APP_STATUS_BAR_COLOR = 'default'
PWA_APP_ICONS = [
    {
        'src': '/static/pwa_assets/icons/manifest-icon-192.png',
        'sizes': '192x192',
        'type': 'image/png',
        'purpose': 'maskable any'
    },
    {
        'src': '/static/pwa_assets/icons/manifest-icon-512.png',
        'sizes': '512x512',
        'type': 'image/png',
        'purpose': 'maskable any'
    }
]
PWA_APP_ICONS_APPLE = [
    {
        'src': '/static/pwa_assets/icons/apple-icon-180.png',
        'sizes': '180x180',
        'type': 'image/png',
        'purpose': 'maskable any'
    }
]
PWA_APP_SPLASH_SCREEN = [
    {
        'src': '/static/pwa_assets/icons/apple-splash-640x1136.jpg',
        'media': '(device-width: 320px) and (device-height: 568px) and (-webkit-device-pixel-ratio: 2)'
    },{
        'src':'/static/pwa_assets/icons/apple-splash-2048-2732.jpg', 
        'media':'(device-width: 1024px) and (device-height: 1366px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)'
    },{
        'src':'/static/pwa_assets/icons/apple-splash-2732-2048.jpg', 
        'media':'(device-width: 1024px) and (device-height: 1366px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)'
    },{
        'src':'/static/pwa_assets/icons/apple-splash-1668-2388.jpg', 
        'media':'(device-width: 834px) and (device-height: 1194px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)'
    },{
        'src':'/static/pwa_assets/icons/apple-splash-2388-1668.jpg', 
        'media':'(device-width: 834px) and (device-height: 1194px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)'
    },{
        'src':'/static/pwa_assets/icons/apple-splash-1536-2048.jpg', 
        'media':'(device-width: 768px) and (device-height: 1024px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)'
    },{
        'src':'/static/pwa_assets/icons/apple-splash-2048-1536.jpg', 
        'media':'(device-width: 768px) and (device-height: 1024px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)'
    },{
        'src':'/static/pwa_assets/icons/apple-splash-1668-2224.jpg', 
        'media':'(device-width: 834px) and (device-height: 1112px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)'
    },{
        'src':'/static/pwa_assets/icons/apple-splash-2224-1668.jpg', 
        'media':'(device-width: 834px) and (device-height: 1112px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)'
    },{
        'src':'/static/pwa_assets/icons/apple-splash-1620-2160.jpg', 
        'media':'(device-width: 810px) and (device-height: 1080px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)'
    },{
        'src':'/static/pwa_assets/icons/apple-splash-2160-1620.jpg', 
        'media':'(device-width: 810px) and (device-height: 1080px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)'
    },{
        'src':'/static/pwa_assets/icons/apple-splash-1284-2778.jpg', 
        'media':'(device-width: 428px) and (device-height: 926px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)'
    },{
        'src':'/static/pwa_assets/icons/apple-splash-2778-1284.jpg', 
        'media':'(device-width: 428px) and (device-height: 926px) and (-webkit-device-pixel-ratio: 3) and (orientation: landscape)'
    },{
        'src':'/static/pwa_assets/icons/apple-splash-1170-2532.jpg', 
        'media':'(device-width: 390px) and (device-height: 844px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)'
    },{
        'src':'/static/pwa_assets/icons/apple-splash-2532-1170.jpg', 
        'media':'(device-width: 390px) and (device-height: 844px) and (-webkit-device-pixel-ratio: 3) and (orientation: landscape)'
    },{
        'src':'/static/pwa_assets/icons/apple-splash-1125-2436.jpg', 
        'media':'(device-width: 375px) and (device-height: 812px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)'
    },{
        'src':'/static/pwa_assets/icons/apple-splash-2436-1125.jpg', 
        'media':'(device-width: 375px) and (device-height: 812px) and (-webkit-device-pixel-ratio: 3) and (orientation: landscape)'
    },{
        'src':'/static/pwa_assets/icons/apple-splash-1242-2688.jpg', 
        'media':'(device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)'
    },{
        'src':'/static/pwa_assets/icons/apple-splash-2688-1242.jpg', 
        'media':'(device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 3) and (orientation: landscape)'
    },{
        'src':'/static/pwa_assets/icons/apple-splash-828-1792.jpg', 
        'media':'(device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)'
    },{
        'src':'/static/pwa_assets/icons/apple-splash-1792-828.jpg', 
        'media':'(device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)'
    },{
        'src':'/static/pwa_assets/icons/apple-splash-1242-2208.jpg', 
        'media':'(device-width: 414px) and (device-height: 736px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)'
    },{
        'src':'/static/pwa_assets/icons/apple-splash-750-1334.jpg', 
        'media':'(device-width: 375px) and (device-height: 667px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)'
    },{
        'src':'/static/pwa_assets/icons/apple-splash-640-1136.jpg', 
        'media':'(device-width: 320px) and (device-height: 568px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)'
    },{
        'src':'/static/pwa_assets/icons/apple-splash-1136-640.jpg', 
        'media':'(device-width: 320px) and (device-height: 568px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)'
    }
]
PWA_APP_SHORTCUTS = [
    {
        'name':'Dashboard',
        'short_name':'home',
        'description':'View your company status',
        'url':'/',
        'icons':PWA_APP_ICONS
    }
]
PWA_APP_DIR = 'ltr'
PWA_APP_LANG = 'en-US'


PWA_MANIFEST = {
    **PWA_APP_SHORTCUTS[0],
    "scope": "/",
    "orientation": PWA_APP_ORIENTATION,
    "background_color": PWA_APP_BACKGROUND_COLOR,
    "theme_color": PWA_APP_THEME_COLOR,
    "status_bar": "default",
    "display":PWA_APP_DISPLAY,
    "start_url":PWA_APP_START_URL,
    "scope":PWA_APP_SCOPE,
    "dir": PWA_APP_DIR,
    "lang": PWA_APP_LANG
}

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

## Push notification

WEBPUSH_SETTINGS = {
   "VAPID_PUBLIC_KEY": "BLIvetyHs7PM5iE4B_t8gm7jk5sxDVRRoehqIZEUP1LxuBDl5rb0PnygtEYIS694g_xW7gjVdXW60AR_j6U48oQ",
   "VAPID_PRIVATE_KEY": "Q6Tv-2uAUDxuzyl34x7qjVv4e9voCOZuCzSxbMbmLy0",
   "VAPID_ADMIN_EMAIL": "alex.tang@jarvisoftech.com"
}

# SMTP Configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp-mail.outlook.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'jayinsystem2022@outlook.com'
EMAIL_HOST_PASSWORD = 'jayin123jayin'

import re
from django.template import base
base.tag_re = re.compile(base.tag_re.pattern, re.DOTALL)