# Generated by Django 5.0.7 on 2024-11-22 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='City',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
