# Generated by Django 5.0.7 on 2024-11-22 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_station_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='Admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='src.admin'),
        ),
    ]
