# Generated by Django 5.0.7 on 2024-11-22 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0004_state_rename_location_station_state_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='station',
            old_name='City',
            new_name='Name',
        ),
        migrations.AlterField(
            model_name='station',
            name='State',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='src.state'),
        ),
        migrations.DeleteModel(
            name='City',
        ),
    ]
