# Generated by Django 5.0.7 on 2024-11-22 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0005_rename_city_station_name_alter_station_state_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='train',
            name='Admin',
        ),
    ]
