# Generated by Django 5.0.7 on 2024-11-23 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0007_remove_coach_coachcode_alter_coach_coachtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='ArriveState',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='train',
            name='DepartState',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
