# Generated by Django 5.0.7 on 2024-11-24 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0009_seat_train'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='CoachType',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
