# Generated by Django 5.0.7 on 2024-11-25 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0010_seat_coachtype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seat',
            old_name='LockTime',
            new_name='last_lock_time',
        ),
        migrations.AlterField(
            model_name='seat',
            name='SeatStatus',
            field=models.CharField(blank=True, choices=[('RESERVED', 'RESERVED'), ('LOCKED', 'LOCKED'), ('AVAILABLE', 'AVAILABLE')], default='AVAILABLE', max_length=50, null=True),
        ),
    ]
