# Generated by Django 5.0.7 on 2024-11-25 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0011_rename_locktime_seat_last_lock_time_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SavedFile',
        ),
        migrations.RemoveField(
            model_name='useractivity',
            name='User',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='Seat',
        ),
        migrations.DeleteModel(
            name='UploadedFile',
        ),
        migrations.DeleteModel(
            name='UserActivity',
        ),
        migrations.AddField(
            model_name='booking',
            name='Seat',
            field=models.ManyToManyField(blank=True, related_name='Client_Seats', to='src.seat'),
        ),
    ]
